library(dplyr)
library(ggplot2)
library(reshape)
dir<-getSrcDirectory(function(x) {x})
setwd(dir)
df<-read.csv('data_deep.csv')
df_opening<-filter(df,sim_id%in%c(1,2,3,5,8,9,10,12,19))
df_delay<-df_opening[,c(1,2,6)]
df_delay$sim_id<-as.factor(df_delay$sim_id)
df_final<-melt(df_delay)
p<-ggplot(data=df_final) 
p+geom_boxplot(aes(x=sim_id, y=value, fill=variable))+ylab('Delay (ms)')
ggsave("deep_opening_width.png")
df_opening<-filter(df,sim_id%in%c(1,2,3,5,8,9,10,12,19,4,11,18,13))
df_delay<-df_opening[,c(1,2,6)]
df_delay$sim_id<-as.factor(df_delay$sim_id)
df_final<-melt(df_delay)
p<-ggplot(data=df_final) 
p+geom_boxplot(aes(x=sim_id, y=value, fill=variable))+ylab('Delay (ms)')
 ## scale_fill_manual(values=c("blue","magenta"))
 ## scale_fill_manual(values=c("#F8766D", "#00BA38"))
ggsave("deep_opening_total.png")
df_opening<-filter(df,sim_id%in%c(1,2,3,5,8,9,10,12,19))
df_ent<-df_opening[,c(3,4,6)]
df_ent$sim_id<-as.factor(df_ent$sim_id)
df_final<-melt(df_ent)
p<-ggplot(data=df_final) 
p+geom_boxplot(aes(x=sim_id, y=value, fill=variable))+
  scale_fill_manual(values=c("blue","magenta"))+ylab('Entropy')
ggsave("deep_opening_width_entr.png")
df_opening<-filter(df,sim_id%in%c(1,2,3,5,8,9,10,12,19,4,11,18,13))
df_ent<-df_opening[,c(3,4,6)]
df_ent$sim_id<-as.factor(df_ent$sim_id)
df_final<-melt(df_ent)
p<-ggplot(data=df_final) 
p+geom_boxplot(aes(x=sim_id, y=value, fill=variable))+
  scale_fill_manual(values=c("blue","magenta"))+ylab('Entropy')
ggsave("deep_opening_total_entr.png")
df_opening<-filter(df,sim_id%in%c(1,2,3,5,8,9,10,12,19))
df_delay<-df_opening[,c(1,2,5)]
#df_delay$sim_id<-as.factor(df_delay$sim_id)
df_final<-melt(df_delay)
p<-ggplot(data=df_final) 
p+geom_boxplot(aes(x=bipole, y=value, fill=variable))+ylab('Delay (ms)')
ggsave("deep_opening_width_bipole.png")
df_opening<-filter(df,sim_id%in%c(1,2,3,5,8,9,10,12,19,4,11,18,13))
df_delay<-df_opening[,c(1,2,5)]
#df_delay$sim_id<-as.factor(df_delay$sim_id)
df_final<-melt(df_delay)
p<-ggplot(data=df_final) 
p+geom_boxplot(aes(x=bipole, y=value, fill=variable))+ylab('Delay (ms)')
ggsave("deep_opening_tot_bipole.png")